import test from "node:test";
import assert from "node:assert/strict";

import { WORD_CORPUS } from "../src/data/word-corpus.js";
import { NONSENSE_POOL } from "../src/data/nonsense-pool.js";
import { isTypeable } from "../src/typing-difficulty.js";

// These files are generated by scripts/build-vocabulary.mjs. The tests guard
// the properties the generator is supposed to hold, so a regeneration that
// goes wrong fails here rather than on screen in front of a child.

const NEVER_SHOW = ["ass", "fag", "kkk", "damn", "hell", "sex", "tit", "cock"];

test("the corpus is the expected size and in frequency order", () => {
  assert.equal(WORD_CORPUS.length, 2000);
  assert.equal(new Set(WORD_CORPUS).size, WORD_CORPUS.length, "no duplicates");
  // Rank is the index, so the order is load-bearing: the most common English
  // words must be at the front.
  assert.ok(WORD_CORPUS.slice(0, 20).includes("the"));
  assert.ok(WORD_CORPUS.slice(0, 20).includes("and"));
});

test("every corpus entry is lowercase, typeable, and long enough to measure", () => {
  for (const word of WORD_CORPUS) {
    assert.match(word, /^[a-z]+$/, `${word} should be plain lowercase letters`);
    assert.ok(word.length >= 2, `${word} is too short to yield a keystroke interval`);
    assert.ok(isTypeable(word), `${word} is not typeable`);
  }
});

test("the nonsense pool stays short and on the home row", () => {
  for (const text of NONSENSE_POOL) {
    assert.ok(text.length >= 2 && text.length <= 3, `${text} should be two or three letters`);
    for (const letter of text) {
      assert.ok("asdfghjkl".includes(letter), `${text} leaves the home row`);
    }
  }
  assert.equal(new Set(NONSENSE_POOL).size, NONSENSE_POOL.length, "no duplicates");
});

test("nonsense and real words do not overlap", () => {
  const corpus = new Set(WORD_CORPUS);
  for (const text of NONSENSE_POOL) {
    assert.ok(!corpus.has(text), `${text} is a real word and belongs in the corpus`);
  }
});

test("nothing unsuitable for a child survives generation", () => {
  const everything = [...WORD_CORPUS, ...NONSENSE_POOL];
  for (const text of everything) {
    for (const bad of NEVER_SHOW) {
      assert.notEqual(text, bad, `"${bad}" must not be shown`);
    }
  }
});

test("the pool is large enough to carry the easy end of a session", () => {
  assert.ok(NONSENSE_POOL.length > 100, `pool of ${NONSENSE_POOL.length} is too small`);
});
